services:
  - type: web
    name: school-erp-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://menemanisha51:Manisha19@cluster0.w8cxa6z.mongodb.net/schoolERP?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: Mohitkey123
      - key: EMAIL_USER
        value: menemanisha51@gmail.com
      - key: EMAIL_PASS
        value: rwslmwwlhbcmeagv
